Table MS_user {
  user_id integer  [primary key]
  user_name varchar
  country varchar
  is_liver integer
  is_listener integer
  gender integer
  adress varchar
  user_status integer
  start_date date

}

Table TR_purchase {
  user_id integer [primary key]
  item_id integer [primary key]
  purchase_date date

}

Table MS_item {
  item_id integer [primary key]
  item_name varchar
  price integer

}



Ref: TR_purchase.user_id > MS_user.user_id // many-to-one
Ref: TR_purchase.item_id > MS_item.item_id // many-to-one
